# Generated by Django 5.1.4 on 2025-04-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='mobile',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
