# Generated by Django 5.1.4 on 2025-04-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_alumni_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='mobile',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
