# Generated by Django 3.2 on 2025-06-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_alumni_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='mobile',
            field=models.CharField(blank=True, help_text="Include country code with '+' and brackets if needed (e.g., +1 (555) 555-5555)", max_length=35, null=True),
        ),
    ]
